### ISSUE TITLE
Encode/decode UUID breaks for >1 leading zero

### ISSUE THREAD

**Issue by Ronan-H** [kfitzgerald/base-id#16]
Hiya 👋 

We ran into a bug for base62 encode/decode when passing a UUID with more than 1 leading zero. The leading zeroes are not preserved after decode. 

Here is a failing test case:

```js
it('should encode/decode a uuid with two leading zeroes', async () => {
    const uuid = '0039d4cd-3923-44ed-a2d5-450776bdfce9';

    should(Base.base62.decode(Base.base62.encode(uuid))).be.exactly('0039D4CD392344EDA2D5450776BDFCE9');
});
```

Results in:

```
AssertionError: expected '39D4CD392344EDA2D5450776BDFCE9' to be '0039D4CD392344EDA2D5450776BDFCE9'
      + expected - actual

      -39D4CD392344EDA2D5450776BDFCE9
      +0039D4CD392344EDA2D5450776BDFCE9
```

Leading zeroes are prepended during encode, but not added back during decode. But actually prepending leading zeroes to a base62 number might not be the right approach because numbers represent the same value regardless of any leading zeroes.

**Comment by kfitzgerald** [comment]
Hey there @Ronan-H !

Thank you for taking the time to report this and provide the test case! Really appreciate it. 

What you discovered is that this base62 implementation doesn't preserve leading zero bytes like base58 does. I can't quite recall exactly why I chose this, but I feel like it had to do with compatibility with other encoder/decoders out there at the time, having used them as a basis for testing and interoperability. Having been nearly 10 years ago now, that's probably much less of an issue now.

The solution is to prepend a magic byte before encoding (`0x01`) and strip it automatically after decode. Unfortunately, this will cause different output between the original base62 encoder/decoder. 

The easiest non-breaking way of dealing with this, is to add a `base62p` class which will do the magic byte handling. This way, existing applications which rely non the non-preserved base62 are not affected. In a future breaking change, we could swap the default base62 algorithm to the magic byte version, which would preserve leading zero bytes by default.

I'll push up a minor revision adding base62p shortly!

Thanks again,
-Kevin

**Comment by kfitzgerald** [comment]
Pushed to npm in v3.3.0
